/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Form;

import Fungsi.Koneksi;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import static java.lang.String.format;
import java.rmi.RemoteException;
import java.sql.Blob;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author STMIK-I-17
 */
public class MenuUtama extends javax.swing.JFrame {

    private Statement stat;
    private ResultSet res;
    private final DefaultTableModel tabModel;
    private PreparedStatement prestat;

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
          String row[]={"kode","nama","produsen","mesin","harga","kapasitas","keterangan","foto"};
         tabModel = new DefaultTableModel(null,row);
         jTable1.setModel(tabModel);
        
         tampilDataKeTabel("","","");
    }
    public void tampilDataKeTabel(String cari,String sort,String rega){
        try{
            String sql="";
            if(!cari.equals("")){
                sql="select * from barang where nama='"
                        + cari + "'";
            }
            else if (sort.equals("yamaha")||sort.equals("honda")||sort.equals("suzuki"))
                    {
                        sql="select * from barang where mesin='"+sort+"'";     
                    }
            else if (rega.equals("mahal"))
            {
                sql="select * from barang order by harga desc";  
            }
             else if (rega.equals("murah"))
             {
                 sql="select * from barang order by harga asc"; 
             }
            
            else{
                sql="select * from barang";
            }
            stat = new Fungsi.Koneksi().koneksiDatabase().createStatement();
            res = stat.executeQuery(sql);
            while(res.next()){
                String kode = res.getString("kode");
                String nama = res.getString("nama");
                String produsen = res.getString("produsen");
                String mesin = res.getString("mesin");
                String harga = res.getString("harga");
                String kapasitas = res.getString("kapasitas");
                String keterangan = res.getString("keterangan");
                String foto = res.getString("foto");
                String data[] = {kode,nama,produsen,mesin,harga,kapasitas,keterangan,foto};
                tabModel.addRow(data);
            }
        }
        catch(Exception e){
            System.out.println("ada error nama field, coba dicek");
        }
    }
    public void hapusPadaForm(){
        int row = tabModel.getRowCount();
        for(int a=0; a<row; a++){
            tabModel.removeRow(0); 
        }        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfmesin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfharga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfkapasitas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfket = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        tffoto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tfprod = new javax.swing.JTextField();
        panelGambar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfkode = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btsimpan = new javax.swing.JButton();
        btubah = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btbatal = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfcari = new javax.swing.JTextField();
        btcariii = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu7 = new javax.swing.JMenu();
        jmyamaha = new javax.swing.JMenuItem();
        jmhonda = new javax.swing.JMenuItem();
        jmsuzuki = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jmmurah = new javax.swing.JMenuItem();
        jmmahal = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem2.setText("jMenuItem2");

        jMenuItem7.setText("jMenuItem7");

        jMenu9.setText("jMenu9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");
        setBackground(new java.awt.Color(102, 255, 0));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("nama motor");

        tfnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamaActionPerformed(evt);
            }
        });

        jLabel2.setText("produsen");

        jLabel3.setText("mesin");

        jLabel6.setText("harga");

        tfharga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfhargaKeyTyped(evt);
            }
        });

        jLabel7.setText("kapasitas mesin");

        jLabel4.setText("keterangan");

        tfket.setColumns(20);
        tfket.setRows(5);
        jScrollPane1.setViewportView(tfket);

        jLabel8.setText("foto");

        tffoto.setEditable(false);
        tffoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffotoActionPerformed(evt);
            }
        });

        jButton1.setText("cari");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("kode barang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfprod)
                    .addComponent(tfnama)
                    .addComponent(tfmesin)
                    .addComponent(tfharga)
                    .addComponent(tfkapasitas)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tffoto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(panelGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(35, 35, 35)
                        .addComponent(tfkode)))
                .addGap(82, 82, 82))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(tffoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfprod, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(tfmesin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfharga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfkapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panelGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("halaman admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btsimpan.setText("simpan");
        btsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btsimpanMouseClicked(evt);
            }
        });

        btubah.setText("ubah");
        btubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btubahMouseClicked(evt);
            }
        });

        bthapus.setText("hapus");
        bthapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bthapusMouseClicked(evt);
            }
        });
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btbatal.setText("batal");
        btbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbatalMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        tfcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcariActionPerformed(evt);
            }
        });

        btcariii.setText("cari barang");
        btcariii.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btcariiiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btsimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btubah, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btbatal)
                        .addGap(18, 18, 18)
                        .addComponent(tfcari, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btcariii)
                        .addGap(23, 23, 23))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsimpan)
                    .addComponent(btubah)
                    .addComponent(bthapus)
                    .addComponent(btbatal)
                    .addComponent(tfcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcariii))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Master");

        jMenuItem1.setText("Ubah Password");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("User");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Barang");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Pemasok");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Logout");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("short by");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenu2.add(jSeparator2);

        jMenu7.setText("mesin");

        jmyamaha.setText("yamaha");
        jmyamaha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmyamahaMouseClicked(evt);
            }
        });
        jmyamaha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmyamahaActionPerformed(evt);
            }
        });
        jMenu7.add(jmyamaha);

        jmhonda.setText("honda");
        jmhonda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmhondaActionPerformed(evt);
            }
        });
        jMenu7.add(jmhonda);

        jmsuzuki.setText("suzuki");
        jmsuzuki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmsuzukiActionPerformed(evt);
            }
        });
        jMenu7.add(jmsuzuki);

        jMenu2.add(jMenu7);

        jMenu8.setText("harga");

        jmmurah.setText("termurah");
        jmmurah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmmurahActionPerformed(evt);
            }
        });
        jMenu8.add(jmmurah);

        jmmahal.setText("termahal");
        jmmahal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmmahalActionPerformed(evt);
            }
        });
        jMenu8.add(jmmahal);

        jMenu2.add(jMenu8);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Laporan");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Keluar");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new UbahPassword().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tfnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnamaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
            
       
        try {  
              int row  = jTable1.getSelectedRow();
             String kode = tabModel.getValueAt(row, 0).toString();
             String nama = tabModel.getValueAt(row, 1).toString();
             String produsen = tabModel.getValueAt(row, 2).toString();
             String mesin = tabModel.getValueAt(row, 3).toString();
             String harga = tabModel.getValueAt(row, 4).toString();
             String kapasitas = tabModel.getValueAt(row, 5).toString();
             String keterangan = tabModel.getValueAt(row, 6).toString();
             String filename = tabModel.getValueAt(row, 7).toString();
              tfnama.setText(nama);
              tfprod.setText(produsen);
              tfmesin.setText(mesin);
              tfharga.setText(harga);
              tfkapasitas.setText(kapasitas);
              tfket.setText(keterangan);
              tffoto.setText(filename);
              tfkode.setText(kode);
           prestat = new Fungsi.Koneksi().koneksiDatabase().prepareStatement("select foto from barang where kode=?");
             //res = stat.executeQuery();
            prestat.setString(1, kode);
            ResultSet res = prestat.executeQuery();
            res.next();
            
            
                byte[] imagedata = res.getBytes("foto");
                format = new ImageIcon(imagedata);
                Image im = format.getImage();
                Image img2 = im.getScaledInstance(panelGambar.getWidth(),panelGambar.getHeight() ,Image.SCALE_DEFAULT);
                ImageIcon img = new ImageIcon(img2);
                panelGambar.setIcon(img);   
            
         } catch (SQLException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG, GIF , and PNG image", "jpg","png","gif");
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();    
        filename = file.getAbsolutePath();
        tffoto.setText(filename);
        try{
        Image image = ImageIO.read(file);
        ImageIcon imageIcon = new ImageIcon(image.getScaledInstance(200,300,200));
        
        panelGambar.setIcon(imageIcon);
        panelGambar.setText("");
        
        File gambar = new File(filename);
        FileInputStream fis = new FileInputStream(gambar);
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        byte[] buf = new byte[1024];
        
        for(int readNum; (readNum=fis.read(buf))!=-1; )
        {
            bos.write(buf,0,readNum);
        }
        photo = bos.toByteArray();
        
        
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsimpanMouseClicked
        // TODO add your handling code here:
            try{
                
                if(!(tfnama.getText().equals("") || tfprod.getText().equals("") || tfmesin.getText().equals("") || tfharga.equals("")))
                {
                   String sql = "insert into barang(kode,nama,produsen,mesin,harga,kapasitas,keterangan,foto) values "
                    + "(?,?,?,?,?,?,?,?)";
            prestat = new Fungsi.Koneksi().koneksiDatabase().prepareStatement(sql);
            prestat.setString(1, tfkode.getText());
            prestat.setString(2,tfnama.getText());
            prestat.setString(3,tfprod.getText());
            prestat.setString(4,tfmesin.getText());
            prestat.setString(5,tfharga.getText());
            prestat.setString(6,tfkapasitas.getText());
            prestat.setString(7,tfket.getText());
            prestat.setBytes(8,photo);
            prestat.executeUpdate();
            JOptionPane.showMessageDialog(null, 
            "Data berhasil disimpan","Informasi",
            JOptionPane.INFORMATION_MESSAGE);
           tfnama.setText("");
           tfharga.setText("");
           tffoto.setText("");
           tfkapasitas.setText("");
           tfket.setText("");
           tfmesin.setText("");
           tfprod.setText("");
           panelGambar.setIcon(null);
           tfkode.setText("");
           hapusPadaForm();
            tampilDataKeTabel("","","");
                }else
                {
                      JOptionPane.showMessageDialog(null, 
                    "kolom harus diisi semua","Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
                    
                 }
        
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, 
                    "kolom tidak boloh kosong atau terdapat kesamaan kode barang","Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
        }
             byte[] photo =null;
           String filename=null;
    }//GEN-LAST:event_btsimpanMouseClicked

    private void bthapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bthapusMouseClicked
        // TODO add your handling code here:
         int row  = jTable1.getSelectedRow();
         String kode = tabModel.getValueAt(row, 0).toString();
        try {
               stat.executeUpdate("delete from barang where kode='"+kode+"'");
                JOptionPane.showMessageDialog(null, 
                    "Data berhasil dihapus","Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
           tfnama.setText("");
           tfharga.setText("");
           tffoto.setText("");
           tfkapasitas.setText("");
           tfket.setText("");
           tfmesin.setText("");
           tfprod.setText("");
           panelGambar.setIcon(null);
           hapusPadaForm();
           tfkode.setText("");
           tampilDataKeTabel("","","");
         

       
    }//GEN-LAST:event_bthapusMouseClicked

    private void btubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btubahMouseClicked
        // TODO add your handling code here   
         int row  = jTable1.getSelectedRow();
          String kode = tabModel.getValueAt(row, 0).toString();
          
        try {  
          //  File gambar = new File(filename);
            //FileInputStream fis = new FileInputStream(gambar);
            //BufferedReader br = new BufferedReader(new InputStreamReader(fis));
            //StringBuffer text = new StringBuffer();
       /*     
        String gambar = new File(filename);
        FileInputStream fis = new FileInputStream(gambar);
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        byte[] buf = new byte[1024];
        
        for(int readNum; (readNum=fis.read(buf))!=-1; )
        {
            bos.write(buf,0,readNum);
        }
        photo = bos.toByteArray();*/
        
        
   
                String sql = "update barang set nama=?,produsen=?,mesin=?,harga=?,kapasitas=?,keterangan=?,foto=? where kode='"+kode+"'";
                prestat = new Fungsi.Koneksi().koneksiDatabase().prepareStatement(sql);
                prestat.setString(1,tfnama.getText());
                prestat.setString(2,tfprod.getText());
                prestat.setString(3,tfmesin.getText());
                prestat.setString(4,tfharga.getText());
                prestat.setString(5,tfkapasitas.getText());
                prestat.setString(6,tfket.getText());
                prestat.setBytes(7,photo);
                prestat.executeUpdate();
                JOptionPane.showMessageDialog(null,
                        "Data berhasil ubah","Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            
             }catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,
                        "kesalahan","Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
        }
        
           tfnama.setText("");
           tfharga.setText("");
           tffoto.setText("");
           tfkapasitas.setText("");
           tfket.setText("");
           tfmesin.setText("");
           tfprod.setText("");
           panelGambar.setIcon(null);
           tfkode.setText("");
           hapusPadaForm();
            tampilDataKeTabel("","","");
             byte[] photo =null;
           String filename=null;
       
        
    }//GEN-LAST:event_btubahMouseClicked

    private void btbatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbatalMouseClicked
        // TODO add your handling code here:
           tfnama.setText("");
           tfharga.setText("");
           tffoto.setText("");
           tfkapasitas.setText("");
           tfket.setText("");
           tfmesin.setText("");
           tfprod.setText("");
           panelGambar.setIcon(null);
           tfkode.setText("");
             hapusPadaForm();
            tampilDataKeTabel("","","");
    }//GEN-LAST:event_btbatalMouseClicked

    private void tfcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcariActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bthapusActionPerformed

    private void tfhargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfhargaKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_tfhargaKeyTyped

    private void btcariiiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btcariiiMouseClicked
        // TODO add your handling code here:
         hapusPadaForm();
        tampilDataKeTabel(tfcari.getText(),"","");
    }//GEN-LAST:event_btcariiiMouseClicked

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
          new User().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jmhondaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmhondaActionPerformed
        // TODO add your handling code here:
        
           tfnama.setText("");
           tfharga.setText("");
           tffoto.setText("");
           tfkapasitas.setText("");
           tfket.setText("");
           tfmesin.setText("");
           tfprod.setText("");
           panelGambar.setIcon(null);
           tfkode.setText("");
        hapusPadaForm();
        tampilDataKeTabel("","honda","");
    }//GEN-LAST:event_jmhondaActionPerformed

    private void jmyamahaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmyamahaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmyamahaMouseClicked

    private void jmyamahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmyamahaActionPerformed
        // TODO add your handling code here:
           tfnama.setText("");
           tfharga.setText("");
           tffoto.setText("");
           tfkapasitas.setText("");
           tfket.setText("");
           tfmesin.setText("");
           tfprod.setText("");
           panelGambar.setIcon(null);
           tfkode.setText("");
        hapusPadaForm();
        tampilDataKeTabel("","yamaha","");
    }//GEN-LAST:event_jmyamahaActionPerformed

    private void jmsuzukiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmsuzukiActionPerformed
        // TODO add your handling code here:
           tfnama.setText("");
           tfharga.setText("");
           tffoto.setText("");
           tfkapasitas.setText("");
           tfket.setText("");
           tfmesin.setText("");
           tfprod.setText("");
           panelGambar.setIcon(null);
           tfkode.setText("");
        hapusPadaForm();
        tampilDataKeTabel("","suzuki","");
    }//GEN-LAST:event_jmsuzukiActionPerformed

    private void jmmurahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmmurahActionPerformed
        // TODO add your handling code here:
         tfnama.setText("");
           tfharga.setText("");
           tffoto.setText("");
           tfkapasitas.setText("");
           tfket.setText("");
           tfmesin.setText("");
           tfprod.setText("");
           panelGambar.setIcon(null);
           tfkode.setText("");
        hapusPadaForm();
        tampilDataKeTabel("","","murah");
    }//GEN-LAST:event_jmmurahActionPerformed

    private void jmmahalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmmahalActionPerformed
        // TODO add your handling code here:
         tfnama.setText("");
           tfharga.setText("");
           tffoto.setText("");
           tfkapasitas.setText("");
           tfket.setText("");
           tfmesin.setText("");
           tfprod.setText("");
           panelGambar.setIcon(null);
           tfkode.setText("");
        hapusPadaForm();
        tampilDataKeTabel("","","mahal");
    }//GEN-LAST:event_jmmahalActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
          Statement stat;
        try {
            stat = new Fungsi.Koneksi().konek.createStatement();
                 ResultSet res = stat.executeQuery("select * from user where status ='aktif'");
                
                if(res.next())
                {
                    String username = res.getString("username");
                    stat.executeUpdate("update user set status=NULL where username='"+username+ "'");
                setVisible(false);
                new Login().setVisible(true);
                 }
        } catch (SQLException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu6MouseClicked

    private void tffotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffotoActionPerformed
 ImageIcon format=null;
 String fname = null;
 int s =0;
 byte[] pimage=null;
 
/* public ImageIcon resizeImage(String imagePath,byte[] pic)
 {
     ImageIcon myImage = null;
     if(imagePath!=null)
     {
         myImage = new ImageIcon(imagePath);
         
     }
     else{
         myImage = new ImageIcon(pic);
     }
     
     Image img = myImage.getImage();
     Image img2 = img.getScaledInstance(panelGambar.getHeight(),panelGambar.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
     
 }
 byte[] getgambar(int kode) throws RemoteException
 {
     try {
          prestat = new Fungsi.Koneksi().koneksiDatabase().prepareStatement("select foto from penjualan where kode=?");
          prestat.setInt(1, kode);
          ResultSet res = prestat.executeQuery();
          byte[] file = null;
          
          while(res.next())
          {
              file = res.getBytes("foto");
          }
          return file;
     }
     catch(Exception e)
     {
         
     }
     return null;
 }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbatal;
    private javax.swing.JButton btcariii;
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btsimpan;
    private javax.swing.JButton btubah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem jmhonda;
    private javax.swing.JMenuItem jmmahal;
    private javax.swing.JMenuItem jmmurah;
    private javax.swing.JMenuItem jmsuzuki;
    private javax.swing.JMenuItem jmyamaha;
    private javax.swing.JLabel panelGambar;
    private javax.swing.JTextField tfcari;
    private javax.swing.JTextField tffoto;
    private javax.swing.JTextField tfharga;
    private javax.swing.JTextField tfkapasitas;
    private javax.swing.JTextArea tfket;
    private javax.swing.JTextField tfkode;
    private javax.swing.JTextField tfmesin;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfprod;
    // End of variables declaration//GEN-END:variables

byte [] photo=null;
String filename=null;
}
